apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ env.K8S_DEPLOYMENT_NAME }}
  namespace: {{ env.K8S_NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ env.IMAGE_NAME }}
  template:
    metadata:
      labels:
        app: {{ env.IMAGE_NAME }}
    spec:
      containers:
        - name: {{ env.IMAGE_NAME }}
          image: {{ env.DOCKER_IMAGE }}
          ports:
              - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "prod"
