apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivohdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivohdemo
  template:
    metadata:
      labels:
        app: trivohdemo
    spec:
      containers:
        - name: trivohdemo
          image: DOCKER_IMAGE
          ports:
              - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "prod"
